name: build

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.manylinux }} ${{ matrix.plat }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python: [ 3.8, 3.9 ]
        manylinux: [ 2010 ]
        plat: [ x86_64 ]
        macos-target: [ "10.10" ]
        exclude:
          - os: macos-latest
            manylinux: 2014
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build
        run: |
          which python3
          python3 -m pip install pip build twine --upgrade
          python3 -m pip install mkl==2019 mkl-include intel-openmp numpy cmake==3.17 pybind11
          python3 -m build
      - name: test
        run: |
          mkdir build_test
          cd build_test
          cmake .. -DUSE_MKL=ON -DBUILD_TEST=ON -DMPI=OFF -DOMP_LIB=GNU -DTBB=ON -DLARGE_BOND=ON
          make
          ./block2_tests
      - name: Release
        uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: dist/*
